In [1]:
# Bài 1
lst = [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]

print("List ban đầu:", lst)
even_index_elements = lst[0::2]
print("Các vị trí chẵn:", even_index_elements)

tpl = tuple(lst)
print("Tuple:", tpl)

dict_comp = {i: v for i, v in enumerate(lst)}
print("Dict:", dict_comp)

set_data = set(lst)
removed_count = len(lst) - len(set_data)

print("Set:", set_data)
print("Số phần tử bị loại trùng:", removed_count)


List ban đầu: [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]
Các vị trí chẵn: [1, 3, 5, 7, 9]
Tuple: (1, 2, 3, 2, 5, 1, 7, 9, 9, 4)
Dict: {0: 1, 1: 2, 2: 3, 3: 2, 4: 5, 5: 1, 6: 7, 7: 9, 8: 9, 9: 4}
Set: {1, 2, 3, 4, 5, 7, 9}
Số phần tử bị loại trùng: 3


In [8]:
# Bài 2:
from pathlib import Path
import json

base = Path('.') 
data_file = base / 'data.txt'
lines = [
    "Dòng 1: Đây là dòng một\n",
    "Dòng 2: Đây là dòng hai\n",
    "Dòng 3: Đây là dòng ba\n",
    "Dòng 4: Đây là dòng bốn\n",
    "Dòng 5: Đây là dòng năm\n",
]

with data_file.open('w', encoding='utf-8') as f:
    f.writelines(lines)

with data_file.open('r', encoding='utf-8') as f:
    read_lines = f.readlines()

for i, ln in enumerate(read_lines, start=1):
    print(f"Dòng {i}: {ln.rstrip()}")

student = {"name": "An", "age": 20, "scores": [8, 9, 7]}
student_file = base / 'student.json'
with student_file.open('w', encoding='utf-8') as f:
    json.dump(student, f, ensure_ascii=False, indent=2)

with student_file.open('r', encoding='utf-8') as f:
    student_from_file = json.load(f)

print("\nJSON đọc từ file:", student_from_file)


Dòng 1: Dòng 1: Đây là dòng một
Dòng 2: Dòng 2: Đây là dòng hai
Dòng 3: Dòng 3: Đây là dòng ba
Dòng 4: Dòng 4: Đây là dòng bốn
Dòng 5: Dòng 5: Đây là dòng năm

JSON đọc từ file: {'name': 'An', 'age': 20, 'scores': [8, 9, 7]}


In [9]:
# Bài 3 
import numpy as np
A = np.arange(12).reshape(3,4)
print("Array:\n", A, "\n")
row2 = A[1]              
col3 = A[:, 2]             
sub = A[1:3, 1:3]          
A_float = A.astype(np.float64)
print("Hàng 2:", row2)
print("Cột 3:", col3)
print("Submatrix:", sub)
print("Dtype mới:", A_float.dtype, "\n")

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Hàng 2: [4 5 6 7]
Cột 3: [ 2  6 10]
Submatrix: [[ 5  6]
 [ 9 10]]
Dtype mới: float64 



In [10]:
# Bài 4 
import pandas as pd
names = ['An','Bình','Châu','Dũng','Hà']
ages = [20,21,22,20,23]
scores = [7.5, 8.0, 6.5, 9.0, 8.5]
s = pd.Series(scores, name='score_series')
df = pd.DataFrame({'name': names, 'age': ages, 'score': scores})
print("Series điểm:\n", s.to_list(), "\n")
print("DataFrame info():")
df.info()
print("\nDataFrame describe():\n", df.describe(), "\n")
filtered = df[df['score'] >= 8]
print("Sinh viên >= 8 điểm:\n", filtered.values.tolist(), "\n")

Series điểm:
 [7.5, 8.0, 6.5, 9.0, 8.5] 

DataFrame info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      object 
 1   age     5 non-null      int64  
 2   score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

DataFrame describe():
             age     score
count   5.00000  5.000000
mean   21.20000  7.900000
std     1.30384  0.961769
min    20.00000  6.500000
25%    20.00000  7.500000
50%    21.00000  8.000000
75%    22.00000  8.500000
max    23.00000  9.000000 

Sinh viên >= 8 điểm:
 [['Bình', 21, 8.0], ['Dũng', 20, 9.0], ['Hà', 23, 8.5]] 



In [11]:
# Bài 5
base = Path('.')
students_csv = base / 'students.csv'
scores_csv = base / 'scores.csv'
students_csv.write_text("1,An\n2,Binh\n3,Chau\n")
scores_csv.write_text("1,8\n2,9\n3,7\n")
df_students = pd.read_csv(students_csv, names=['id','name'])
df_scores = pd.read_csv(scores_csv, names=['id','score'])
merged = pd.merge(df_students, df_scores, on='id')
report = merged.groupby(['id','name'])['score'].agg(['min','max','mean']).reset_index()
report.columns = ['id','name','score_min','score_max','score_mean']
report.to_csv('report.csv', index=False)
print("Report:\n", report.to_csv(index=False))

Report:
 id,name,score_min,score_max,score_mean
1,An,8,8,8.0
2,Binh,9,9,9.0
3,Chau,7,7,7.0



In [12]:

# Bài 6 
a = np.arange(1,5).reshape(4,1)
b = np.array([10,20,30,40,50]).reshape(1,5)
prod = a * b
sqrt_prod = np.sqrt(prod)
log_prod = np.log(prod)
stats_axis1 = {
    'min': prod.min(axis=1),
    'max': prod.max(axis=1),
    'mean': prod.mean(axis=1),
    'std': prod.std(axis=1)
}
print("a =\n", a)
print("b =\n", b)
print("a*b =\n", prod)
print("sqrt(a*b)=\n", np.round(sqrt_prod,4))
print("log(a*b)=\n", np.round(log_prod,4))
print("Stats axis=1:", stats_axis1, "\n")

a =
 [[1]
 [2]
 [3]
 [4]]
b =
 [[10 20 30 40 50]]
a*b =
 [[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]
sqrt(a*b)=
 [[ 3.1623  4.4721  5.4772  6.3246  7.0711]
 [ 4.4721  6.3246  7.746   8.9443 10.    ]
 [ 5.4772  7.746   9.4868 10.9545 12.2474]
 [ 6.3246  8.9443 10.9545 12.6491 14.1421]]
log(a*b)=
 [[2.3026 2.9957 3.4012 3.6889 3.912 ]
 [2.9957 3.6889 4.0943 4.382  4.6052]
 [3.4012 4.0943 4.4998 4.7875 5.0106]
 [3.6889 4.382  4.7875 5.0752 5.2983]]
Stats axis=1: {'min': array([10, 20, 30, 40]), 'max': array([ 50, 100, 150, 200]), 'mean': array([ 30.,  60.,  90., 120.]), 'std': array([14.14213562, 28.28427125, 42.42640687, 56.56854249])} 



In [13]:

# Bài 7
data = {
    'name': ['An','Bình','Châu','Dũng'],
    'age': [20, np.nan, 22, 21],
    'score': [8.5, np.nan, 7.0, 9.0],
    'city': ['Hà Nội', 'HCM', np.nan, 'Hà Nội']
}
df7 = pd.DataFrame(data)
print("Original isna:\n", df7.isna(), "\n")
age_mean = df7['age'].mean()
score_median = df7['score'].median()
df7['age'] = df7['age'].fillna(age_mean)
df7['score'] = df7['score'].fillna(score_median)
df7['city'] = df7['city'].fillna('Unknown')
df7['city'] = df7['city'].astype('category')
def level(x):
    if x >= 8: return 'Good'
    if x >= 6: return 'Average'
    return 'Bad'
df7['score_level'] = df7['score'].apply(level)
# chuẩn hóa tuổi
age_mean2 = df7['age'].mean()
age_std2 = df7['age'].std(ddof=0)
df7['age_normalized'] = (df7['age'] - age_mean2) / age_std2
print("age_cleaned =", df7['age'].tolist())
print("score_cleaned =", df7['score'].tolist())
print("city (category) =", df7['city'])
print("score_level =", df7['score_level'].tolist())
print("age_normalized =", df7['age_normalized'].tolist())


Original isna:
     name    age  score   city
0  False  False  False  False
1  False   True   True  False
2  False  False  False   True
3  False  False  False  False 

age_cleaned = [20.0, 21.0, 22.0, 21.0]
score_cleaned = [8.5, 8.5, 7.0, 9.0]
city (category) = 0     Hà Nội
1        HCM
2    Unknown
3     Hà Nội
Name: city, dtype: category
Categories (3, object): ['HCM', 'Hà Nội', 'Unknown']
score_level = ['Good', 'Good', 'Average', 'Good']
age_normalized = [-1.414213562373095, 0.0, 1.414213562373095, 0.0]


In [ ]:
# bài 8
from pathlib import Path
import json
import pandas as pd
import re

logs_dir = Path('logs')
if not logs_dir.exists():
    print('Thư mục logs/ không tồn tại. Vui lòng tạo và thêm các file JSON.')
else:
    records = []
    date_re = re.compile(r"\d{4}-\d{2}-\d{2}")
    for p in sorted(logs_dir.glob('*.json')):
        m = date_re.search(p.stem)
        if not m:
            continue
        date_str = m.group(0)
        try:
            payload = json.loads(p.read_text(encoding='utf-8'))
        except Exception as e:
            print(f"Bỏ qua file không đọc được: {p.name} -> {e}")
            continue
        user = payload.get('user')
        action = payload.get('action')
        duration = payload.get('duration')
        try:
            duration = float(duration) if duration is not None else 0.0
        except Exception:
            print(f"duration không hợp lệ trong {p.name}, đặt về 0")
            duration = 0.0
        records.append({'date': pd.to_datetime(date_str).date(),
                        'user': user, 'action': action, 'duration': duration,
                        'source_file': p.name})

    if not records:
        print('Không tìm thấy record log hợp lệ trong logs/.')
    else:
        df_logs = pd.DataFrame.from_records(records)
        summary = df_logs.groupby('date', as_index=False)['duration'].sum()
        summary = summary.sort_values('date')
        for _, row in summary.iterrows():
            print(f"Date: {row['date']}, Total Duration: {row['duration']}")
        out_file = Path('daily_report.csv')
        summary.to_csv(out_file, index=False)
        print(f"Saved daily report to: {out_file.resolve()}")

Date: 2024-01-01, Total Duration: 5.0
Date: 2024-01-02, Total Duration: 3.0
Saved daily report to: C:\code\python\ss8\daily_report.csv
