In [1]:
import numpy as np

# bài 1
arr1 = np.arange(1, 11, dtype=np.int32)
print('arr1 =', arr1)
print('shape1 =', arr1.shape)
print('dtype1 =', arr1.dtype)

arr1_float = arr1.astype(np.float32)
print('dtype_float =', arr1_float.dtype)
print('arr1_float =', arr1_float)

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int32)
print('arr2 =')
print(arr2)
print('shape2 =', arr2.shape)
print('dtype2 =', arr2.dtype)   

arr1 = [ 1  2  3  4  5  6  7  8  9 10]
shape1 = (10,)
dtype1 = int32
dtype_float = float32
arr1_float = [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
arr2 =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape2 = (3, 3)
dtype2 = int32


In [4]:
import numpy as np

# bài 2
arr1 = np.arange(1, 11)
print('arr1 =', arr1)

first_elem = arr1[0]
last_elem = arr1[-1]
middle_elem = arr1[5]
print('first_elem =', first_elem)
print('last_elem =', last_elem)
print('middle_elem =', middle_elem)

sliced_arr = arr1[2:5]
print('sliced_arr =', sliced_arr.tolist())

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row2 = arr2[1]
col3 = arr2[:, 2]
print('row2 =', row2.tolist())
print('col3 =', col3.tolist())

arr1 = [ 1  2  3  4  5  6  7  8  9 10]
first_elem = 1
last_elem = 10
middle_elem = 6
sliced_arr = [3, 4, 5]
row2 = [4, 5, 6]
col3 = [3, 6, 9]


In [ ]:
# bài 3
import numpy as np
np.random.seed(42)

A = np.random.randint(1, 100, size=(3, 3))
print(A)
print('\nMin:', A.min())
print('Max:', A.max())
print('Sum:', A.sum())
print('Mean:', A.mean())
print('STD:', A.std())
print('\nSumOfColumn:', A.sum(axis=0))
print('MeanOfColumn:', A.mean(axis=0))
print('\nSumOfRow:', A.sum(axis=1))
print('MeanOfRow:', A.mean(axis=1))

[[52 93 15]
 [72 61 21]
 [83 87 75]]

Min: 15
Max: 93
Sum: 559
Mean: 62.111111111111114
STD: 26.42996802640032

SumOfColumn: [207 241 111]
MeanOfColumn: [69.         80.33333333 37.        ]

SumOfRow: [160 154 245]
MeanOfRow: [53.33333333 51.33333333 81.66666667]


In [5]:
# bài 4
import numpy as np
np.random.seed(0)

A = np.random.randint(1, 20, size=(3, 3))
B = np.array([10, 20, 30])     
B_row = B.reshape(1, 3)      
print('A:\n', A)
print('\nB:', B)

print('\nA + B (broadcast 1D):\n', A + B)
print('\nA - B_row (explicit 1x3):\n', A - B_row)

A:
 [[13 16  1]
 [ 4  4  8]
 [10 19  5]]

B: [10 20 30]

A + B (broadcast 1D):
 [[23 36 31]
 [14 24 38]
 [20 39 35]]

A - B_row (explicit 1x3):
 [[  3  -4 -29]
 [ -6 -16 -22]
 [  0  -1 -25]]


In [6]:
# bài 5
import numpy as np
import time
np.random.seed(2)

a = np.random.randint(1, 21, size=10)
print('a =', a)

squares_vec = np.square(a)
roots_vec = np.sqrt(a)
print('\nsquares (vectorized):', squares_vec)
print('roots (vectorized):', roots_vec)

print('\nadd 5 (ufunc):', np.add(a, 5))
print('multiply by 2 (ufunc):', np.multiply(a, 2))

t0 = time.perf_counter()
s_loop = [x*x for x in a]
t1 = time.perf_counter()
t_loop = t1 - t0
t0 = time.perf_counter()
s_vec = a * a
t1 = time.perf_counter()
t_vec = t1 - t0
print(f'\nloop time: {t_loop:.6f} s, vectorized time: {t_vec:.6f} s')

a = [ 9 16 14  9 12 19 12  9  8  3]

squares (vectorized): [ 81 256 196  81 144 361 144  81  64   9]
roots (vectorized): [3.         4.         3.74165739 3.         3.46410162 4.35889894
 3.46410162 3.         2.82842712 1.73205081]

add 5 (ufunc): [14 21 19 14 17 24 17 14 13  8]
multiply by 2 (ufunc): [18 32 28 18 24 38 24 18 16  6]

loop time: 0.000058 s, vectorized time: 0.000022 s


In [7]:
# bài 6
import numpy as np
np.random.seed(3)

A = np.random.randint(1, 10, size=(4, 4))
print(A)

print('\nTổng theo cột (axis=0):', A.sum(axis=0))
print('Trung bình theo cột (axis=0):', A.mean(axis=0))
print('Độ lệch chuẩn theo cột (axis=0):', A.std(axis=0))

print('\nTổng theo hàng (axis=1):', A.sum(axis=1))
print('Trung bình theo hàng (axis=1):', A.mean(axis=1))
print('Độ lệch chuẩn theo hàng (axis=1):', A.std(axis=1))

[[9 4 9 9]
 [1 6 4 6]
 [8 7 1 5]
 [8 9 2 7]]

Tổng theo cột (axis=0): [26 26 16 27]
Trung bình theo cột (axis=0): [6.5  6.5  4.   6.75]
Độ lệch chuẩn theo cột (axis=0): [3.20156212 1.80277564 3.082207   1.47901995]

Tổng theo hàng (axis=1): [31 17 21 26]
Trung bình theo hàng (axis=1): [7.75 4.25 5.25 6.5 ]
Độ lệch chuẩn theo hàng (axis=1): [2.16506351 2.04633819 2.68095132 2.6925824 ]


In [8]:
# bài 7
import numpy as np
np.random.seed(4)

A = np.random.randint(1, 10, size=(4, 4))
print(A)
print('\nTổng theo cột (axis=0):', A.sum(axis=0))
print('Trung bình theo cột (axis=0):', A.mean(axis=0))
print('\nTổng theo hàng (axis=1):', A.sum(axis=1))
print('Trung bình theo hàng (axis=1):', A.mean(axis=1))

[[8 6 2 9]
 [8 9 3 8]
 [8 8 9 5]
 [3 7 5 4]]

Tổng theo cột (axis=0): [27 30 19 26]
Trung bình theo cột (axis=0): [6.75 7.5  4.75 6.5 ]

Tổng theo hàng (axis=1): [25 28 30 19]
Trung bình theo hàng (axis=1): [6.25 7.   7.5  4.75]


In [ ]:
# bài 8
import numpy as np
import time
np.random.seed(5)

A = np.random.randint(1, 20, size=(5, 5))
B = np.array([10, 20, 30, 40, 50])
print('A:\n', A)
print('\nB:', B)

sum_b = A + B  
diff_b = A - B
sqrt_A = np.sqrt(A)
add5 = np.add(A, 5)
print('\nKết quả cộng (broadcasting):\n', sum_b)
print('\nKết quả trừ (broadcasting):\n', diff_b)
print('\nKết quả căn bậc hai (ufunc):\n', np.round(sqrt_A, 8))
print('\nKết quả cộng 5 vào mảng (ufunc):\n', add5)

t0 = time.perf_counter()
out_loop = np.empty_like(A)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        out_loop[i, j] = A[i, j] + B[j]
t1 = time.perf_counter()
t_loop = t1 - t0
t0 = time.perf_counter()
out_b = A + B
t1 = time.perf_counter()
t_vec = t1 - t0
print(f'\nThời gian vòng lặp: {t_loop:.6f} s, broadcasting: {t_vec:.6f} s')

A:
 [[ 4 15 16  7 17]
 [10  9  5  8 17]
 [17  8 13 16 18]
 [ 8 17 13 14 12]
 [ 2 16 19 10 11]]

B: [10 20 30 40 50]

Kết quả cộng (broadcasting):
 [[14 35 46 47 67]
 [20 29 35 48 67]
 [27 28 43 56 68]
 [18 37 43 54 62]
 [12 36 49 50 61]]

Kết quả trừ (broadcasting):
 [[ -6  -5 -14 -33 -33]
 [  0 -11 -25 -32 -33]
 [  7 -12 -17 -24 -32]
 [ -2  -3 -17 -26 -38]
 [ -8  -4 -11 -30 -39]]

Kết quả căn bậc hai (ufunc):
 [[2.         3.87298335 4.         2.64575131 4.12310563]
 [3.16227766 3.         2.23606798 2.82842712 4.12310563]
 [4.12310563 2.82842712 3.60555128 4.         4.24264069]
 [2.82842712 4.12310563 3.60555128 3.74165739 3.46410162]
 [1.41421356 4.         4.35889894 3.16227766 3.31662479]]

Kết quả cộng 5 vào mảng (ufunc):
 [[ 9 20 21 12 22]
 [15 14 10 13 22]
 [22 13 18 21 23]
 [13 22 18 19 17]
 [ 7 21 24 15 16]]

Thời gian vòng lặp: 0.000098 s, broadcasting: 0.000028 s
